# Generated by Django 5.1.2 on 2026-02-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salarie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(max_length=20)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('type_contrat', models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('VACATAIRE', 'Vacataire'), ('STAGIAIRE', 'Stagiaire'), ('ALTERNANT', 'Alternant')], default='CDI', max_length=30)),
                ('date_debut_contrat', models.DateField()),
                ('date_fin_contrat', models.DateField(blank=True, null=True)),
                ('poste', models.CharField(max_length=100)),
                ('etablissement', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
