# Generated by Django 5.1.2 on 2026-02-18 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarie',
            name='role',
            field=models.CharField(choices=[('SALARIE', 'Salarié'), ('RH', 'RH'), ('ADMIN', 'Admin')], default='SALARIE', max_length=10),
        ),
    ]
