# Generated by Django 5.1.2 on 2026-02-10 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece_identite', models.CharField(max_length=50)),
                ('numero_secu', models.CharField(max_length=20)),
                ('adresse', models.TextField()),
                ('iban', models.CharField(max_length=34)),
                ('documents_officiels', models.JSONField(blank=True, null=True)),
                ('complementaires', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('salarie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dossier', to='users.salarie')),
            ],
        ),
    ]
