# Generated by Django 5.1.2 on 2026-02-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dossier',
            old_name='complementaires',
            new_name='infos_complementaires',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='documents_officiels',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='piece_identite',
        ),
        migrations.AddField(
            model_name='dossier',
            name='contact_nom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dossier',
            name='contact_telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='dossier',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dossier',
            name='lien_familial',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='dossier',
            name='lieu_naissance',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='dossier',
            name='pays',
            field=models.CharField(default='France', max_length=100),
        ),
        migrations.AddField(
            model_name='dossier',
            name='ville',
            field=models.CharField(default='Paris', max_length=100),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='numero_secu',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
