# Generated by Django 5.1.2 on 2026-02-18 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demande',
            old_name='created_at',
            new_name='date_demande',
        ),
    ]
