# Generated by Django 5.1.2 on 2026-02-18 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0002_rename_created_at_demande_date_demande'),
        ('paie', '0001_initial'),
        ('users', '0002_salarie_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Paiement',
            new_name='Paie',
        ),
    ]
